# Rakefile

require "sinatra/activerecord/rake"

namespace :db do
  task :load_config do
    require_relative "./application"
  end
end

namespace :db do
  desc "Drop all tables"
  task :drop_tables => :environment do
    # require_relative "./application"
    conn = ActiveRecord::Base.connection
    tables = conn.tables # Get a list of all tables in the database

    # Exclude tables that should not be dropped, like schema_migrations
    # tables.delete("schema_migrations")

    tables.each do |table|
      puts "Dropping table #{table}"
      conn.drop_table(table, force: :cascade) # Drop the table, cascading to dependent tables
    end
    
    # Write the schema file
    Rake::Task["db:schema:dump"].invoke
  end
end